### ISSUE TITLE
Way to exclude `own` sniff from a ruleset

### ISSUE THREAD

**Issue by simPod** [PHPCSStandards/PHP_CodeSniffer#240]
## Is your feature request related to a problem?

Having `ruleset.xml` with `<ruleset name="MyRuleSet"...` automatically includes all sniffs (own sniffs) under `Sniffs` directory. I'd like to have a way to only selectively include those.

## Describe the solution you'd like

`<exclude ref="MyRuleSet.Somegroup.Sniffname" />`

**Comment by jrfnl** [comment]
@simPod You mean like:
```xml
    <rule ref="MyRuleSet.Somegroup.Sniffname">
        <severity>0</severity>
    </rule>
```

**Comment by simPod** [comment]
Oh, that seems to be a way to do that. Thanks.
