### ISSUE TITLE
auto_detect_line_endings is deprecated

### ISSUE THREAD

**Issue by simPod** [PHPCSStandards/PHP_CodeSniffer#342]
## Describe the bug

Runner sets deprecated directive. Should we remove it?

https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated

### Code sample

https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/4bbc82053ee4e8fb79f3e4c950caaf95ba487586/src/Runner.php#L306

### To reproduce

Run on I guess php 8.1+

## Expected behavior

No error
## Versions (please complete the following information)

| | |
|-|-|
| Operating System | Macos sonoma
| PHP version | 8.1
| PHP_CodeSniffer version | 3.8.1
| Install type | Composer

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by jrfnl** [comment]
@simPod Thanks for your concern, but this is a non-issue.

The PHP 8.1 deprecation has been silenced via the `@` for PHPCS 3.x and the statement has already been removed for PHPCS 4.0.

**Comment by Mardl** [comment]
This would help in 3.x. 

if (version_compare(PHP_VERSION, '8.1.0', '<')) {
    @ini_set('auto_detect_line_endings', true);
}
