### ISSUE TITLE
Referenced Sniff: <my_custom_sniff_name> doesn't exist

### ISSUE THREAD

**Issue by naveen17797** [PHPCSStandards/PHP_CodeSniffer#377]
I am trying to exclude my custom sniff in the **phpcs configuration xml** file, i get the referenced sniff doesn't exist error.
 I understand that the error is due to the fact that i haven't installed my sniff yet, but i have a specific usecase that requires this. I want to able to check if that sniff is installed, if yes then it needs to be excluded from phpcs **via the configuration xml file**. Is it possible to acheive this? I am using the latest version 3.9.0.

Thank you

**Comment by jrfnl** [comment]
@naveen17797 As far as I can think of, that's not possible at this time.

Can you expand a bit on your usecase ?

**Comment by naveen17797** [comment]
@jrfnl  Thanks, i will look for alternatives
