### ISSUE TITLE
Possible Incorrect Title in XML doc for Sniff Generic.Formatting.NoSpaceAfterCastStandard

### ISSUE THREAD

**Issue by jpoliveira08** [PHPCSStandards/PHP_CodeSniffer#383]
### Description
I have noticed an inconsistency in the title of the XML file for the Generic.Formatting.NoSpaceAfterCast sniff. Currently, the title states "Space After Casts," while the description says "Spaces are not allowed after casting operators." However, upon further examination, it seems that the correct interpretation should be "No Space After Casts" as the subsequent sniff has a title "Space After Casts" with a description stating "Exactly one space is allowed after a cast."

### Proposed Changes:

- Propose updating the title of Generic.Formatting.NoSpaceAfterCastStandard.xml to "No Space After Casts."

### Contributor Note:
This issue would serve as my first contribution to open source. I would be eager to take ownership of resolving it.

**Comment by jrfnl** [comment]
@jpoliveira08 Thanks for reporting this. I look forward to your PR. If you need information on what is expected, please read the [CONTRIBUTING](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/5a2a3769d2713de829a16a29c8bffad673eca6b5/.github/CONTRIBUTING.md#writing-sniff-documentation) information.
