### ISSUE TITLE
Document all the sniffs

### ISSUE THREAD

**Issue by ghost** [PHPCSStandards/PHP_CodeSniffer#434]
## Is your feature request related to a problem?
There is no documentation for the sniffs. We can only reason about a sniff from a class name. Neither Wiki pages represents the destiny of the sniffs nor Sniff interface has a method like `getDescription()` or `getDefinition()` with code samples before/after.

## Describe the solution you'd like
Add new method to the interface or maintain the Wiki.

## Additional context (optional)

- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@javaDeveloperKid No clue what you are trying to suggest here, but your basic premise seems ill-informed.

The [vast majority](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/148) of PHPCS native sniffs have documentation and you can access the docs applicable to any standard via `phpcs --generator=Text --standard=...`.

There's a discussion going in #317 to see about also making this information accessible via a web interface or via the wiki.

**Comment by jrfnl** [comment]
FYI: While it doesn't directly address this issue, PR #447 is a proposal to improve the help screens, including improved information on the help screen about finding documentation/rules for your ruleset.

Reviews and testing of that PR would be appreciated.
