### ISSUE TITLE
Allow to register sniff via FQCN

### ISSUE THREAD

**Issue by javaDeveloperKid** [PHPCSStandards/PHP_CodeSniffer#435]
## Is your feature request related to a problem?
I often fail to create a rule ref based on a FQCN. Why can't we just reference a Sniff via it's FQCN? The life would be much more simple.

## Additional context (optional)

- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
I understand you are coming from CS-Fixer, but PHPCS works differently. Give it a chance on its own merits.

The change suggested in this ticket is not something which will be accepted in PHPCS.

**Comment by jrfnl** [comment]
There is no tricky pattern and an issue tracker is not a helpdesk.

The sniff names translate 1-on-1 to the files in a (registered) standard:

Registered standard: `MyStandard` => `path/to/MyStandard`.
File: `path/to/MyStandard/Sniffs/Category/RuleNameSniff.php`
SniffName: `MyStandard.Category.RuleName`

Also see:
![image](https://github.com/PHPCSStandards/PHP_CodeSniffer/assets/663378/4030cc7c-ac64-498b-addd-b0274c7cbf72)

**Comment by jrfnl** [comment]
> Is there a helpdesk?


No, though for support - as per the [CONTRIBUTING guide](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md#supportquestions-about-using-php_codesniffer) -, the suggested channels are Discussions and StackOverflow, not the issue ticketing system.
