### ISSUE TITLE
Undefined array key in Generic.WhiteSpace.ScopeIndent

### ISSUE THREAD

**Issue by SunflowerFuchs** [PHPCSStandards/PHP_CodeSniffer#437]
## Describe the bug
When checking a specific file (see minimal code sample), phpcs throws an `undefined array key` error. 

### Code sample
```php
<?php

match (true) {
    default => [
        'unrelated' => '',
        'example' => array_filter(
            array_map(
                function () {
                    return null;
                },
                []
            )
        )
    ]
};
```
(Yes, i know the code is very convoluted, it's very much an edge-case)
Interestingly enough, the unrelated array key is relevant, if removed then the error doesn't occur anymore. 

### Custom ruleset
No custom ruleset defined.

### To reproduce
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php`
3. See error message displayed
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Undefined array key 68 in /app/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php on line 1481
|       | The error originated in the Generic.WhiteSpace.ScopeIndent sniff on line 1481. (Internal.Exception)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

## Expected behavior
Show an understandable/fixable error, instead of a generic error coming from inside of phpcs. 

## Versions

| | |
|-|-|
| Operating System | Linux 6.6 (in docker)
| PHP version | 8.1 & 8.3
| PHP_CodeSniffer version | 3.8.1 & 3.9.1
| Standard | whatever the default is (PEAR?)
| Install type | composer

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by DannyvdSluijs** [comment]
I can confirm this is reproducible on the current `master` branch (commit b0ecdf10fa5a15bbf341b6dd75d1b23bd803aaaf).

The line causing the error can be seen at
https://github.com/DannyvdSluijs/PHP_CodeSniffer_Continuation/blob/master/src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php#L1481

At frist glance there is no obvious culprit and the same issue can be reproduced using version `3.7.1`, `3.6.2`. Using `git bisect` it seems that 97f78982711bdf122200dc37be6f33dfbd4aa4dd is causing the issue which was aimed to solve https://github.com/squizlabs/PHP_CodeSniffer/issues/3287

**Comment by jrfnl** [comment]
I've been digging into this one and it looks like it is a pretty complex bug in the `File::findStartOfStatement()` method related to the handling of `match` expressions, which is causing this behaviour.

Currently working on fixing that bug. Once that bug is fixed, I'll have to see if reported issue can still be reproduced and if there is anything within the `ScopeIndent` sniff, which would still need fixing.

**Comment by jrfnl** [comment]
Pff.. this was complex one. PR #502 should fix it though. Testing appreciated.
