### ISSUE TITLE
Auto fix of Squiz.Operators.ComparisonOperatorUsage

### ISSUE THREAD

**Issue by p-pichet** [PHPCSStandards/PHP_CodeSniffer#493]
## Is your feature request related to a problem?
Add the auto fix on the Squiz.Operators.ComparisonOperatorUsage

## Describe the solution you'd like
When run phpcbf with the rule Squiz.Operators.ComparisonOperatorUsage, fix the case of strict comparission : 
```php
if ($test == false) {
```
becomes 
```php 
if ($test == false) {
```

## Additional context (optional)

- [ x] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@p-pichet Thank you for your interest in contributing to PHP_CodeSniffer.

Unfortunately, the fixer you are suggesting would not be accepted, as per the [guidelines in the CONTRIBUTING doc](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md#requestingsubmitting-new-features):

> Please note: Auto-fixers will only be accepted for "non-risky" sniffs. If a fixer could cause parse errors or a change in the behaviour of the scanned code, the fixer will NOT be accepted in PHP_CodeSniffer and may be better suited to an external standard.

External standards are not bound by the same rules, so if you want to use a similar sniff, which does have an auto-fixer, I suggest you use the `Universal.Operators.StrictComparisons` sniff from [PHPCSExtra](https://github.com/phpcsstandards/phpcsextra?tab=readme-ov-file#universaloperatorsstrictcomparisons-wrench-bar_chart-books).

**Comment by p-pichet** [comment]
Sorry miss this part.
