### ISSUE TITLE
Add Fixer method to remove a line

### ISSUE THREAD

**Issue by andrewnicols** [PHPCSStandards/PHP_CodeSniffer#517]
## Is your feature request related to a problem?

When writing some sniff fixes, it's necessary to remove an entire line. Currently there is no helper for this.
This is particularly helpful when writing sniffs for phpdocs.

## Describe the solution you'd like

```php
$phpcsFile->fixer->beginChangeset();
$phpcsFile->fixer->removeLineAtPointer($stackPtr);
$phpcsFile->fixer->endChangeset();
````

## Additional context (optional)

- [x] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@andrewnicols I'd like to see a more thorough specification of what you'd expect such a method to do, as it feels like the current description is wide open to interpretation.

Here are just some of the questions which pop up in my mind and there's bound to be more:
* Would this remove the line the pointer is on ? Or the next line ? (i.e. from the end of the line)
* What if the pointer is somewhere in the middle of a line ?
* Would this only apply to "blank" lines (including comment blank lines) or to lines containing any content ?
* If the latter, a generic method seems kind of dangerous as it would not be able to validate that it is the "correct" line/content to be removed. I.e. the sniff would need to validate the line contents before removing it anyway, so why delegate the removing to a specialty method which cannot verify the sniff has done the required validation ?

**Comment by jrfnl** [comment]
Closing for lack of reply. As things are, this issue is not actionable. The issue can be reopened for further discussion if the requested additional information is added.
