### ISSUE TITLE
Explicitly say that CLI --exclude option disables only 3-part codes, entire sniffs, not 4-part ones

### ISSUE THREAD

**Issue by arsel-5lvxa7b1** [PHPCSStandards/PHP_CodeSniffer#536]
## Is your feature request related to a problem?
Hello, IDK if it's the right place for me to talk about this, but we use phpcs without ruleset.xml and couldn't figure out why a 4-part code exclude wasn't working. The error message only says about rule not being found.

## Describe the solution you'd like
Explicitly say in wiki and in CLI help that --exclude option doesn't work with 4-part codes.

To be frank, our version of phpcs is quite old (3.4.0) so it may be fixed in newer versions, but I only could find about it from this comment in old repo:
https://github.com/squizlabs/PHP_CodeSniffer/issues/1755#issuecomment-482394520

This could save others time to find out why their exclude is not working.

- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md) and this is not a [support question](https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions).
- [ ] I intend to create a pull request to implement this feature.

**Comment by arsel-5lvxa7b1** [comment]
@jrfnl while I agree with this, the error was very hard to Google. Maybe I should've read the wiki yes, but without pointing out the specific section, in advanced usage nonetheless (I wouldn't consider it advanced btw), it's hard to find it for me.

My user story is like this: see error, wonder why it's invalid, Google it, can't find my use case, go to github, usage is in wiki, search by exclude, nothing comes up aside from the console help. Continue googling, trying to change the search query, until I find the issue I mentioned. 

Even when I went to advanced usage now (btw hard to find that page on mobile), I couldn't make out which section do I need. Limiting results to specific sniffs sounds like an include list only.

After the error text change it could be easier to find why, I agree. And I know how hard it is to maintain open source projects :D

**Comment by jrfnl** [comment]
@arsel-5lvxa7b1 I hear you and improving the error message, as per #344, is a "blessed task", so once the work on that is finished, it will be merged and included whichever release we're at by that time.

Having said that, I understand your inclination to use a search engine to find answers, but the GitHub website is not super-SEO friendly (which is outside my control), so I'd always recommend checking the project documentation (README/wiki) first.

If the documentation can be improved, I'm happy to accept suggestions, but the prerequisite for that will always be reading the docs first....

**Comment by arsel-5lvxa7b1** [comment]
Alright, let's close this then, if I'll have an idea how to improve the wiki, I'll do a pull request, assuming I'll have the time :D
