### ISSUE TITLE
Modifier keyword order for PER 2.0

### ISSUE THREAD

**Issue by rikvdh** [PHPCSStandards/PHP_CodeSniffer#567]
For PER 2.0 we need a 'updated' variant for checking modifier keywords. In PSR-12/PER 1.0, only abstract, final and static were checked (see `PSR2.Methods.MethodDeclaration`). But for PER 2.0, this is extended:

> 4.6 Modifier Keywords[¶](https://www.php-fig.org/per/coding-style/#46-modifier-keywords)
> Classes, properties, and methods have numerous keyword modifiers that alter how the engine and language handles them. When present, they MUST be in the following order:
> 
> - Inheritance modifier: abstract or final
> - Visibility modifier: public, protected, or private
> - Scope modifier: static
> - Mutation modifier: readonly
> - Type declaration
> - Name
>
> All keywords MUST be on a single line, and MUST be separated by a single space.

An updated version of `PSR2.Methods.MethodDeclaration` might be a good approach and might be quite simple to do for someone wanting to get into developing sniffs.

- [X] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md) and this is not a [support question](https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions).
- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@rikvdh I don't understand what change you are proposing/suggesting. Maybe adding some code samples would help (also for the other issue a good idea).

If I look at the specs above, the `PSR2.Methods.MethodDeclaration` sniff already handles the checking of the order perfectly for methods as the `readonly` keyword does not apply to methods and methods can also not be typed in this way.

**Comment by jrfnl** [comment]
Also note that for properties this is checked via the `PSR2.Classes.PropertyDeclaration` sniff and, again, that sniff already handles this correctly.

**Comment by rikvdh** [comment]
I was not sure if this was fully covered yet, I'll check this.

**Comment by jrfnl** [comment]
> I was not sure if this was fully covered yet, I'll check this.

It may be, it may not be. Please check before opening an issue....

**Comment by rikvdh** [comment]
Ok, this was not fully covered for PER 2.0 currently. Solved via PHPCSExtra.
