### ISSUE TITLE
Test files mess with code completition

### ISSUE THREAD

**Issue by mabar** [PHPCSStandards/PHP_CodeSniffer#636]
## Is your feature request related to a problem?

Codesniffer tests have a lot of definitions that match common keywords and it messes up code completition (in PHPStorm):

- names of test functions like `func`, `true`, `false` and `null` show up along with coresponding PHP keywords/constants/etc., sometimes even before them
- in code in global scope variable types get combined (e.g. inside conditions) for variables with the same name (e.g. `$container`) even when proper phpdoc is defined in the file. In case of the DI container, we have defined method `get()` with generic return type which does not work (it is random, can't reliably replicate) because of the combined type and the PSR container ([used in tests](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/9e60f9f8748736d3d06fea8ef26dccbdc5ba4902/src/Standards/PSR12/Tests/Files/FileHeaderUnitTest.9.inc#L6-L7)) having method with the same name.

When working with tens of packages, including third-party, working around the problem gets quite annoying. I am currently using `drupal/core-vendor-hardening` package to remove the test directories, with following config:

```json
	"extra": {
		"drupal-core-vendor-hardening": {
			"squizlabs/php_codesniffer": [
				"tests",
				"src/Standards/Generic/Tests",
				"src/Standards/MySource/Tests",
				"src/Standards/PEAR/Tests",
				"src/Standards/PSR1/Tests",
				"src/Standards/PSR2/Tests",
				"src/Standards/PSR12/Tests",
				"src/Standards/Squiz/Tests",
				"src/Standards/Zend/Tests",
				"src/Standards/Generic/Tests",
				"src/Standards/Generic/Tests"
			]
		}
	},
```

## Describe the solution you'd like

- remove tests from released package
- or move them into a single tests directory so they are easier to remove via Composer plugin

## Additional context

![image](https://github.com/user-attachments/assets/03ec01b9-8041-417b-a046-cfd5513dbb64)
![image](https://github.com/user-attachments/assets/6be6159d-99c2-416d-bae3-96ec82e92772)

- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md) and this is not a [support question](https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions).
- [x] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@mabar This is a known issue and will be fixed in the 4.0 release.

See https://github.com/squizlabs/PHP_CodeSniffer/issues/1908 and https://github.com/squizlabs/PHP_CodeSniffer/issues/548 for historical context and the reasoning for the decision to change this in the 4.0 release (and not before).
