### ISSUE TITLE
Support PHP 8.4 property hooks

### ISSUE THREAD

**Issue by jnoordsij** [PHPCSStandards/PHP_CodeSniffer#731]
## Describe the solution you'd like

PHP 8.4 has been recently released, introducing [property hooks](https://www.php.net/manual/en/migration84.new-features.php#migration84.new-features.core.property-hooks) which allows for easier customization to get and set logic of properties.

This new syntax yields some errors when linted with current setup. A small example I've created:
```php
<?php

namespace Foo;

class Foo
{
    private string $privateBar = 'bar';

    public string $bar {
        get => $this->privateBar;
        set(string $bar) {
            $this->privateBar = $bar;
        }
    }
}
```

When running `phpcs --standard=PSR12 foo.php` this yields
```
FILE: ...foo.php
------------------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 4 LINES
------------------------------------------------------------------------------
  9 | ERROR | There must not be more than one property declared per statement
 10 | ERROR | Visibility must be declared on property "$this"
 11 | ERROR | There must not be more than one property declared per statement
 11 | ERROR | Visibility must be declared on property "$bar"
 12 | ERROR | There must not be more than one property declared per statement
 12 | ERROR | Visibility must be declared on property "$this"
------------------------------------------------------------------------------
```

I'd expect no errors linting this.

## Additional context (optional)

There might be additional new PHP 8.4 syntax that require additional changes. Maybe this should be listed on #106 or a new tracking issue for PHP 8.4 syntax? I could not find an existing source for tracking 8.4 compatibility.

- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md) and this is not a [support question](https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions).
- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
Oh and this comment from me on the Internals mailinglist should also help illuminate why so many sniffs will need updates and how problematic property hooks are: https://externals.io/message/123048#123118

**Comment by jrfnl** [comment]
I've now opened the PHP 8.4 syntax overview ticket: https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/734

I think it would be a good idea to close this ticket in favour of the overview ticket.

**Comment by jnoordsij** [comment]
Thanks a lot for your detailed explanation on the issue at hand, and also on all the time you spent on this earlier in the process trying to raise your concerns. I can only imagine how hard getting up-to-date with this amount of new syntax can be, so I fully understand that it might be a very lengthy process before this lands. 

My main reason for raising this issue was mostly to have a place to track progress for future reference, both for me and others. I think #734 is a perfect overview to find that now, so I'll gladly close this in favor of that!

**Comment by jrfnl** [comment]
@jnoordsij Thank you for your understanding.
